n1=(input("Diga o primeiro número:"))
a=(n1.isalnum())
b=(n1.isalpha())
c=(n1.isnumeric())
d=(n1.isupper())
e=(n1.islower())

print ("Você digitou {}".format(n1))
print ("O tipo do valor digitado é:", type(n1))
print ("O valor digitado é alfanumérico? {}".format(a))
print ("O valor digitado é apenas alfa? {}".format(b))
print ("O valor digitado é apenas numérico? {}".format(c))
print ("O valor digitado é todo feito em maíusculo? {}".format(d))
print ("O valor digitado é todo feito em minúsculo? {}".format(e))