print("Olá, este é um programa para somar 2 numeros diferentes, vamos começar!")
n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
s = (n1+n2)
print ("O valor entre ambos os números é ", s)
