v3=int(input("Digite um número para saber sua tabuada"))
print("seu valor x1 é",v3*1 )
print("seu valor x2 é", v3*2)
print("seu valor x3 é", v3*3)
print("seu valor x4 é", v3*4)
print("seu valor x5 é", v3*5)
print("seu valor x6 é", v3*6)
print("seu valor x7 é", v3*7)
print("seu valor x8 é", v3*8)
print("seu valor x9 é", v3*9)
print("seu valor x10 é", (v3*10))